name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    container: gradle:7.3.3-jdk11
    services:
      database:
        image: quality11/mapuvic-database:0.0.1
        ports:
          - 5432:5432
    steps:
      - 
        name: checkout maps
        uses: actions/checkout@v2.4.0
      - 
        name: build api
        run: gradle api:build
        env:
          DATABASE_PORT: 5432
  build-frontend:
    runs-on: ubuntu-latest
    container: gradle:7.3.3-jdk11
    steps:
      - 
        name: checkout maps
        uses: actions/checkout@v2.4.0
      - 
        name: build app
        run: gradle app:build

    
 
      

